server: 
  port: 5014

spring:
  application:
    name: user-management-service

    

# swagger-ui custom path
springdoc: 
  swagger-ui: 
     path: /swagger-ui.html
     

iamserver:
  base-url: https://iam.weshopifyapp.in/scim2
  role-api: /Roles
  user-api: /Users
  user-name: admin
  password: admin
  role-api-schema: urn:ietf:params:scim:schemas:extension:2.0:Role
  

