spring: 
 application: 
   name: weshopify-category-service
 datasource: 
   username: '${CATEGORIES_DB_USER:root}'
   password: '${CATEGORIES_DB_PASSWORD:root}' 
   url: 'jdbc:${CATEGORIES_DB_TYPE:mysql}://${CATEGOIRIES_DB_HOST:localhost}:${CATEGORIES_DB_PORT:3306}/${CATEGORIES_DB_SCHEMA:weshopify_app_categories}'
 jpa:
    hibernate:
      ddl-auto: '${CATEGORIES_DB_DDL_AUTO:update}'
    show-sql: true    
 data:
    redis:
      host: '${REDIS_SERVER_HOST:cache.weshopifyapp.in}'
      port: '${REDIS_SERVER_PORT:80}'
      password: '${REDIS_SERVER_PASSWORD:Redis123$}'
     

   
server:
    port: 5016
    
